[package]
name = "smoji_bot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.8"
rand = "0.8.4"

[dependencies.tokio]
features = ["rt-multi-thread"]
version = "1.13.0"